using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LobbyManager : MonoBehaviour {

    //Who is connecting?
    //What are their characters?
    //Is this lobby at capacity?
    //Does this lobby have AI? If so may replace!

    // Use this for initialization

    public movementController[] players;
    
    void Start()
    {
        players = FindObjectsOfType(typeof(movementController)) as movementController[];//GameObject.FindObjectOfType(typeof(movementController)) as movementController;//GetComponents<movementController>();

    }

    //// Update is called once per frame
    //void Update () {

    //}
}
